export const SPREADSHEET_IMPORT_COPY = {
  button: "Importar planilhas",
  title: "Importar período comercial",
  subtitle: "Selecione o relatório de atendimentos comerciais e uma ou mais planilhas de ordens de serviço.",
  attendanceLabel: "Atendimentos comerciais",
  attendanceHint: "O atendimento identifica a atendente; a venda só é confirmada por uma OS de instalação finalizada.",
  serviceOrdersLabel: "Ordens de serviço",
  serviceOrdersHint: "Selecione uma ou mais planilhas de OS do mesmo período.",
  privacy: "O processamento acontece neste navegador. As planilhas não são enviadas para um servidor.",
  cancel: "Cancelar",
  confirm: "Processar período",
  processing: "Processando planilhas…",
  emptyStatus: "Nenhum período importado",
  importedStatus: "Período carregado",
} as const;
