import { createContext, useContext, type ReactNode } from "react";
import { GroupedColumnChart, MultiDonutChart } from "@/garden/charts";
import { Badge, KpiCard, LoadingScreen, Row, Stack, Surface, Text } from "@/garden/foundations";
import { CheckCheckIcon, MapPinnedIcon, TriangleAlertIcon, UsersIcon } from "@/garden/foundations/assets/icons/icons";
import { TOKENS } from "@/garden/tokens";
import { CANCELLATIONS_COPY } from "../copy/cancellationsCopy";
import { useCancellationsController } from "../controller/useCancellationsController";
import type { CancellationsSnapshot } from "../types/cancellations";
import type { CancellationsViewModel } from "../viewModel/buildCancellationsViewModel";

const chartFrame = { gridLine: TOKENS.color.stroke.subtle, textMuted: TOKENS.color.content.muted, textPrimary: TOKENS.color.content.primary, textSubtle: TOKENS.color.content.subtle, tooltipBackground: TOKENS.color.surface.elevated, tooltipBorder: TOKENS.color.stroke.strong, tooltipInverseBackground: TOKENS.color.surface.inverse, tooltipInverseText: TOKENS.color.surface.base };
const reasonColors = [TOKENS.color.feedback.danger, TOKENS.color.feedback.warning, TOKENS.color.chart.info, TOKENS.color.category.accentPink, TOKENS.color.chart.neutral] as const;

const PeriodSelectorContext = createContext<ReactNode>(null);

function Header({ vm }: { vm: CancellationsViewModel }) {
  const periodSelector = useContext(PeriodSelectorContext);
  return <header className="page-header"><Stack gap={TOKENS.spacing[8]}><Text size="xs" weight={800} tone="brand" style={{ textTransform: "uppercase", letterSpacing: TOKENS.typography.letterSpacing.eyebrow }}>{CANCELLATIONS_COPY.eyebrow}</Text><Text size="title-lg" weight={800} block>{CANCELLATIONS_COPY.title}</Text><Text size="md" tone="secondary" block>{CANCELLATIONS_COPY.description}</Text></Stack><Row align="center" gap={TOKENS.spacing[10]} style={{ flexWrap: "wrap" }}><Badge variant="info">{vm.sourceLabel}</Badge>{periodSelector}</Row></header>;
}

function Reasons({ vm }: { vm: CancellationsViewModel }) {
  const segments = vm.reasons.map((reason, index) => ({ percentage: reason.share, color: reasonColors[index % reasonColors.length] }));
  return <Surface tone="subtle" padding={TOKENS.spacing[24]} style={{ border: `1px solid ${TOKENS.color.stroke.default}` }}><Stack gap={TOKENS.spacing[20]}><Stack gap={TOKENS.spacing[4]}><Text size="xl" weight={800}>{CANCELLATIONS_COPY.reasonsTitle}</Text><Text size="sm" tone="muted">{CANCELLATIONS_COPY.reasonsDescription}</Text></Stack><div className="cancellation-reasons-content"><MultiDonutChart segments={segments} trackColor={TOKENS.color.stroke.subtle} size={190} strokeWidth={10} tooltip={{ heading: "Motivos de cancelamento", valueLabels: vm.reasons.map((reason) => reason.label), counts: vm.reasons.map((reason) => reason.count) }}><Stack align="center" gap={TOKENS.spacing[2]}><Text size="value" weight={800}>{vm.summary.total}</Text><Text size="xs" tone="muted">cancelamentos</Text></Stack></MultiDonutChart><Stack gap={TOKENS.spacing[10]} style={{ flex: 1 }}>{vm.reasons.map((reason, index) => <Row key={reason.id} align="center" gap={TOKENS.spacing[10]}><span className="reason-dot" style={{ background: reasonColors[index % reasonColors.length] }} /><Stack gap={TOKENS.spacing[2]} style={{ flex: 1 }}><Row align="center" gap={TOKENS.spacing[6]}><Text size="sm" weight={700}>{reason.label}</Text>{reason.avoidable && <Badge size="xs" variant="warning">tratável</Badge>}</Row><Text size="xs" tone="muted">{reason.share.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}% do total</Text></Stack><Text size="sm" weight={800}>{reason.count}</Text></Row>)}</Stack></div></Stack></Surface>;
}

function Locations({ vm }: { vm: CancellationsViewModel }) {
  const maximum = Math.max(...vm.locations.map((location) => location.current), 1);
  return <Surface tone="subtle" padding={TOKENS.spacing[24]} style={{ border: `1px solid ${TOKENS.color.stroke.default}` }}><Stack gap={TOKENS.spacing[20]}><Stack gap={TOKENS.spacing[4]}><Text size="xl" weight={800}>{CANCELLATIONS_COPY.locationsTitle}</Text><Text size="sm" tone="muted">{CANCELLATIONS_COPY.locationsDescription}</Text></Stack><Stack gap={TOKENS.spacing[12]}>{vm.locations.map((location) => { const improving = location.current <= location.previous; return <Stack key={location.location} gap={TOKENS.spacing[8]} style={{ padding: TOKENS.spacing[12], borderRadius: TOKENS.radius[10], background: TOKENS.color.surface.card }}><Row align="center" justify="space-between" gap={TOKENS.spacing[12]}><Stack gap={TOKENS.spacing[2]}><Text size="sm" weight={800}>{location.location}</Text><Text size="xs" tone="muted">Anterior: {location.previous}</Text></Stack><Stack align="flex-end" gap={TOKENS.spacing[2]}><Text size="lg" weight={800}>{location.current}</Text><Text size="xs" weight={700} tone={null} style={{ color: improving ? TOKENS.color.feedback.success : TOKENS.color.feedback.warning }}>{location.growth}</Text></Stack></Row><div className="cancellation-location-track"><div style={{ width: `${(location.current / maximum) * 100}%`, background: improving ? TOKENS.color.feedback.success : TOKENS.color.feedback.warning }} /></div></Stack>; })}</Stack></Stack></Surface>;
}

function Recent({ vm }: { vm: CancellationsViewModel }) {
  return <Surface tone="subtle" padding={TOKENS.spacing[24]} style={{ border: `1px solid ${TOKENS.color.stroke.default}` }}><Stack gap={TOKENS.spacing[20]}><Row align="flex-start" justify="space-between" gap={TOKENS.spacing[16]}><Stack gap={TOKENS.spacing[4]}><Text size="xl" weight={800}>{CANCELLATIONS_COPY.recentTitle}</Text><Text size="sm" tone="muted">{CANCELLATIONS_COPY.recentDescription}</Text></Stack><Badge variant="neutral">{vm.recentCancellations.length} registros</Badge></Row><div className="cancellations-table" role="table" aria-label="Cancelamentos recentes"><div className="cancellations-table-head" role="row"><Text size="xs" weight={700} tone="muted">PROTOCOLO</Text><Text size="xs" weight={700} tone="muted">CLIENTE</Text><Text size="xs" weight={700} tone="muted">MOTIVO</Text><Text size="xs" weight={700} tone="muted">PLANO</Text><Text size="xs" weight={700} tone="muted">LOCALIDADE</Text><Text size="xs" weight={700} tone="muted">STATUS</Text></div>{vm.recentCancellations.map((cancellation) => <div className="cancellations-table-row" role="row" key={cancellation.id}><Stack gap={TOKENS.spacing[2]}><Text size="xs" weight={700} truncate title={cancellation.id}>{cancellation.id}</Text><Text size="xs" tone="muted">{cancellation.date}</Text></Stack><Text size="sm" weight={600} truncate title={cancellation.customer}>{cancellation.customer}</Text><Text size="sm" truncate title={cancellation.reason}>{cancellation.reason}</Text><Text size="sm" tone="secondary" truncate title={cancellation.plan}>{cancellation.plan}</Text><Text size="sm" truncate title={cancellation.location}>{cancellation.location}</Text><Badge size="sm" variant={cancellation.status === "Concluído" ? "neutral" : "warning"}>{cancellation.status}</Badge></div>)}</div></Stack></Surface>;
}

function Content({ vm }: { vm: CancellationsViewModel }) {
  return <main className="app-main"><Stack gap={TOKENS.spacing[24]}><Header vm={vm} /><section className="kpi-grid" aria-label="Indicadores de cancelamentos"><KpiCard label="Cancelamentos no mês" value={vm.summary.total} subLabel={vm.summary.growth} subLabelTrend="down" icon={<UsersIcon />} iconColor={TOKENS.color.feedback.danger} iconBg={TOKENS.color.feedback.dangerSoft} /><KpiCard label="Redução absoluta" value={vm.summary.avoided} subLabel="cancelamentos a menos" icon={<CheckCheckIcon />} iconColor={TOKENS.color.feedback.success} iconBg={TOKENS.color.feedback.successSoft} /><KpiCard label="Principal motivo" value={vm.summary.mainReason} subLabel={vm.summary.mainReasonShare} icon={<TriangleAlertIcon />} iconColor={TOKENS.color.feedback.warning} iconBg={TOKENS.color.feedback.warningSoft} /><KpiCard label="Localidade em atenção" value={vm.summary.location} subLabel={vm.summary.locationCount} icon={<MapPinnedIcon />} iconColor={TOKENS.color.feedback.info} iconBg={TOKENS.color.feedback.infoSoft} /></section><Surface tone="subtle" padding={TOKENS.spacing[24]} style={{ border: `1px solid ${TOKENS.color.stroke.default}` }}><Stack gap={TOKENS.spacing[20]}><Row align="flex-start" justify="space-between" gap={TOKENS.spacing[16]}><Stack gap={TOKENS.spacing[4]}><Text size="xl" weight={800}>{CANCELLATIONS_COPY.trendTitle}</Text><Text size="sm" tone="muted">{CANCELLATIONS_COPY.trendDescription}</Text></Stack><Row gap={TOKENS.spacing[14]}><Row align="center" gap={TOKENS.spacing[6]}><span className="legend-dot" style={{ background: TOKENS.color.feedback.danger }} /><Text size="xs" tone="muted">{vm.comparison.currentLabel}</Text></Row><Row align="center" gap={TOKENS.spacing[6]}><span className="legend-dot" style={{ background: TOKENS.color.content.subtle }} /><Text size="xs" tone="muted">{vm.comparison.previousLabel}</Text></Row></Row></Row><GroupedColumnChart labels={vm.trend.labels} primaryValues={vm.trend.current} secondaryValues={vm.trend.previous} primaryLabel={vm.comparison.currentLabel} secondaryLabel={vm.comparison.previousLabel} primaryColor={TOKENS.color.feedback.danger} secondaryColor={TOKENS.color.content.subtle} frame={chartFrame} height={260} ariaLabel="Comparativo mensal dos cancelamentos" /></Stack></Surface><section className="cancellations-insight-grid"><Reasons vm={vm} /><Locations vm={vm} /></section><Recent vm={vm} /><Text size="xs" tone="subtle" style={{ textAlign: "right" }}>Atualizado em {vm.updatedAt}</Text></Stack></main>;
}

export function CancellationsPage({ snapshot, periodSelector }: { snapshot?: CancellationsSnapshot; periodSelector?: ReactNode }) {
  const { viewModel, isLoading } = useCancellationsController(snapshot);
  if (isLoading || !viewModel) return <LoadingScreen visible onExitComplete={() => undefined} label="Carregando análise de cancelamentos" />;
  return <PeriodSelectorContext.Provider value={periodSelector}><Content vm={viewModel} /></PeriodSelectorContext.Provider>;
}
